### ISSUE TITLE
Using module in external project

### ISSUE THREAD

**Issue by NorthWindH** [pvginkel/VisualGit#41]
Hello there VisualGit team and/or Peter,

I've used the file VisualGit.Package\Attributes\ProvideSolutionProperties.cs in an external project (https://visualstudiogallery.msdn.microsoft.com/69e19ea6-4442-4cb6-b300-044dd21f02bd) since it seems to be the best way to hook a VSPackage up with the windows registry in as least an intrusive way as possible.

I've included a licensing note on the project's distribution page as well as including the notice that ships with VisualGit inline on the page.

Is this adequate for me to continue to use your work? If not, please let me know what I need to change.

Actually now that I'm here, I think that I will also provide a link to this repo.

Looking forward to your response.

Best regards.

**Comment by pvginkel** [comment]
That's totally fine. Thank you for letting me know.

**Comment by NorthWindH** [comment]
Perfect. Thank you for getting back!

I've also officially open sourced the project under MIT. I believe that MIT is a less strict license than your own Apache 2. Hopefully that's not an issue? As I understand it, MIT would apply to all of my work while work taken from VisualGit would retain its Apache2 license.

Repo https://bitbucket.org/LSS_NorthWind/physical-solution-folders/src

Again, please let me know if that's a problem at all and I'm sure we can work something out.

Cheers!

**Comment by pvginkel** [comment]
I don't have a problem with that.
